#set up properties
PROJECT_ID: books-418412

server:
    port: ${DEFAULT_PORT:8087}

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: main
        gcp:
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:books-418412}
                enabled: true
application:
    clients:
        - username: root
          password: root
          roles: READ,WRITE