#set up properties
PROJECT_ID: qwiklabs-gcp-2a9ed15c791d9269

server:
    port: ${DEFAULT_PORT:80}

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: master
        gcp:
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:qwiklabs-gcp-2a9ed15c791d9269}
                enabled: true